# These are supported funding model platforms
github: emmamartins
open_collective: pytonik # Replace with a single Open Collective username
ko_fi: pytonik # Replace with a single Ko-fi username
liberapay: pytonik # Replace with a single Liberapay username
issuehunt: pytonik
